In [6]:
import numpy as np
import pandas as pd


In [2]:
arr = np.array([[2,3,4] , [5,6,7] , [8,9,12]])
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 12]])

In [3]:
arr[1,1]

6

In [4]:
arr.shape

(3, 3)

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr.itemsize

8

In [15]:
np.array(arr,dtype = np.float64)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 12.]])

In [16]:
np.size(arr)

9

In [18]:
arr0 = np.zeros([3,3])
arr0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr1 = np.ones([4,4])
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
rr = range(1,10)
rr

range(1, 10)

In [26]:
ranges  = np.arange(1,10,2)
ranges

array([1, 3, 5, 7, 9])

In [29]:
lines = np.linspace(11.0 , 21.0 , 12)
lines

array([11.        , 11.90909091, 12.81818182, 13.72727273, 14.63636364,
       15.54545455, 16.45454545, 17.36363636, 18.27272727, 19.18181818,
       20.09090909, 21.        ])

In [31]:
arr.reshape

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 12]])

In [35]:
arr1 = arr.ravel()
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 12])

In [52]:
print("this is the minimum number from the array ",arr.min())
print("this is the maximum number from the array ",arr.max())
print("this is the sum of total number from the array",arr.sum())
print("this is the sum of total number from the array by axis-0",arr.sum(axis=0))
print("this is the sum of total number from the array by axis-1",arr.sum(axis=1))
print("this is the sqrt of array",np.sqrt(arr))
print("\nSTANDERD DEVIATION for the array is ",np.std(arr))
print("\n MEAN for the array is ",np.mean(arr))
print("\n median for the array is ",np.median(arr))



this is the minimum number from the array  2
this is the maximum number from the array  12
this is the sum of total number from the array 56
this is the sum of total number from the array by axis-0 [15 18 23]
this is the sum of total number from the array by axis-1 [ 9 18 29]
this is the sqrt of array [[1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.46410162]]

STANDERD DEVIATION for the array is  2.973130702279923

 MEAN for the array is  6.222222222222222

 median for the array is  6.0
